[project]
name = "evo-tunes-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deap>=1.4.3",
    "fastapi>=0.117.1",
    "fluidsynth>=0.2",
    "music21>=9.7.1",
    "uvicorn>=0.37.0",
]
